server:
    port: 8087

spring:

    config:
        import: optional:sensitiveInformation.yml #change the sensitiveInformationExample name with its credentials

    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: create-drop

    sql:
        init:
            platform: postgres

    datasource:
        url: jdbc:postgresql://localhost:5432/dentalmoovi
        username: postgres
        password: ${dataBasePassword}
        driver-class-name: org.postgresql.Driver

    mail:
        host: ${mailHost}
        port: 587
        protocol: smtp
        username: ${email}
        password: ${mailPassword}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true

logging:
    level:
        '[org.hibernate.SQL]': DEBUG

jwt:
    secret: ${jwtSecret}